// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can re-run any of the FlutterFire setup binaries to add them.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can re-run any of the FlutterFire setup binaries to add them.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can re-run any of the FlutterFire setup binaries to add them.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can re-run any of the FlutterFire setup binaries to add them.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALYJEDGH6aaxkQqWcPxIl_u2J_kiGbGjo',
    appId: '1:721879809008:android:6078048ecaf6155901bb35',
    messagingSenderId: '721879809008',
    projectId: 'dazzles-hrms',
    storageBucket: 'dazzles-hrms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMPoZuU96jNCwJGk1rrFSGlvq4St2gg8E',
    appId: '1:721879809008:ios:0e09408ce88b077901bb35',
    messagingSenderId: '721879809008',
    projectId: 'dazzles-hrms',
    storageBucket: 'dazzles-hrms.firebasestorage.app',
    iosBundleId: 'com.crisant.dazzleshrms',
  );
}
